spring:
  application:
    name: fleet-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fleet}
    username: ${SPRING_DATASOURCE_USERNAME:fleet}
    password: ${SPRING_DATASOURCE_PASSWORD:fleet}
